### PR TITLE
FC changes to incorporate SIP requirements

### PR DESCRIPTION
**Pull request by pranavnbapat**

### CODE REVIEW

**Comment by arruda** [comment]
@pranavnbapat Just to confirm here, so I would suggest to keep for this PR only the animal and parcel stuff, then we reuse the FarmCalendarActivity model for both the operations and observations that are required by the sips on specific PRs. (see PR #26)

**Comment by arruda** [comment]
And I also recomend reseting the migrations instead of creating new ones. that is, just delete the 001_initia_migration.py and create it again with the changes... we don't need to keep track of these schema changes right now since we don't actually have a prod DB yet.

**Comment by pranavnbapat** [comment]
Yes, it's a good idea. We can remove all the migration files and reset the migrations. I'll do that.

**Review by arruda — APPROVED** [review]
seems good

**Pull request merged**
